export {
  useSkillListQuery,
  useLazySkillListQuery,
  useTotalSkillsQuery,
  useSkillCreateMutation,
  useSkillDetailsQuery,
  useLazySkillDetailsQuery,
  useSkillCreateVersionMutation,
  useSkillUpdateMutation,
  useDeleteSkillMutation,
  useSetSkillDefaultVersionMutation,
  useLazySkillExportMdQuery,
  useSkillImportMutation,
  useUpdateSkillRelationMutation,
  useGetApplicationSkillsQuery,
  useLazyGetApplicationSkillsQuery,
} from './skillsApi';
